### ISSUE TITLE
Wrong type argument: stringp, package-desc

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/clj-refactor.el#369]
## Expected behavior
`clj-refactor` correctly installed from MELPA

## Actual behavior
This message appears in `*Compile-Log*` buffer:
```
Compiling file /home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el at Mon Apr 10 10:58:50 2017
clj-refactor.el:39:1:Error: Wrong type argument: stringp, package-desc
```

## Steps to reproduce the problem
- <kbd>M-x package-install</kbd>
- insert `clj-refactor`
- press <kbd>RET</kbd>

### clj-refactor.el version information
`clj-refactor-20170407.553`

### CIDER version information
```
;; CIDER 0.15.0-snapshot, nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_121
```

### Leiningen or Boot version
Leiningen 2.7.1

### Emacs version
GNU Emacs 26.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2017-04-10

### Operating system
Ubuntu 16.04.2 LTS

**Comment by benedekfazekas** [comment]
hm... looks weird. i reinstalled the clj-refactor (same version, latest head) and had no such problems. i am emacs version `25.1.1` tho... noticed that you are on latest, cutting edge emacs. any chance that causes the problem?

**Comment by manuel-uberti** [comment]
Could be, it works on `25.1.1.`.

**Comment by manuel-uberti** [comment]
Sorry, but why was this closed?

**Comment by benedekfazekas** [comment]
the problem does not seem to be specific to `clj-refactor.el` tbh. feel free to reopen if you think otherwise (and preferably have some extra info backing it ;) ).

**Comment by manuel-uberti** [comment]
I managed to install it, but upon issuing with the default binding <kbd>C-c C-m</kb> I get this:
```
Debugger entered--Lisp error: (wrong-type-argument stringp package-desc)
  signal(wrong-type-argument (stringp package-desc))
  epl-package-from-lisp-file("/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el")
  epl-package-from-file("/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el")
  (epl-package-version (epl-package-from-file source))
  (let* ((source (pkg-info-library-source library)) (version (epl-package-version (epl-package-from-file source)))) (pkg-info--show-version-and-return version show))
  pkg-info-library-version(clj-refactor)
  (or orig-version (pkg-info-library-version library))
  (let* ((package (or package (if (stringp library) (intern library) library))) (orig-version (condition-case nil (pkg-info-library-original-version library) (error nil))) (lib-version (or orig-version (pkg-info-library-version library))) (pkg-version (condition-case nil (pkg-info-package-version package) (error nil))) (version (if (and pkg-version (not (version-list-= lib-version pkg-version))) (format "%s (package: %s)" (pkg-info-format-version lib-version) (pkg-info-format-version pkg-version)) (pkg-info-format-version lib-version)))) (pkg-info--show-version-and-return version show))
  pkg-info-version-info(clj-refactor)
  cljr--version(t)
  cljr--inject-jack-in-dependencies()
  #[0 "\300 \207" [cljr--inject-jack-in-dependencies] 1]()
  eval-after-load(cider #[0 "\300 \207" [cljr--inject-jack-in-dependencies] 1])
  byte-code("\300\301\302\"\210\303\304\305\"\210\306\307\310\311#\210\312\211\2032
```

**Comment by manuel-uberti** [comment]
I also get something similar when just opening a .clj file:
```
Debugger entered--Lisp error: (wrong-type-argument stringp package-desc)
  signal(wrong-type-argument (stringp package-desc))
  epl-package-from-lisp-file("/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el")
  epl-package-from-file("/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el")
  (epl-package-version (epl-package-from-file source))
  (let* ((source (pkg-info-library-source library)) (version (epl-package-version (epl-package-from-file source)))) (pkg-info--show-version-and-return version show))
  pkg-info-library-version(clj-refactor)
  (or orig-version (pkg-info-library-version library))
  (let* ((package (or package (if (stringp library) (intern library) library))) (orig-version (condition-case nil (pkg-info-library-original-version library) (error nil))) (lib-version (or orig-version (pkg-info-library-version library))) (pkg-version (condition-case nil (pkg-info-package-version package) (error nil))) (version (if (and pkg-version (not (version-list-= lib-version pkg-version))) (format "%s (package: %s)" (pkg-info-format-version lib-version) (pkg-info-format-version pkg-version)) (pkg-info-format-version lib-version)))) (pkg-info--show-version-and-return version show))
  pkg-info-version-info(clj-refactor)
  (s-trim (pkg-info-version-info (quote clj-refactor)))
  (s-replace "snapshot" "-SNAPSHOT" (s-trim (pkg-info-version-info (quote clj-refactor))))
  (let ((version (s-replace "snapshot" "-SNAPSHOT" (s-trim (pkg-info-version-info (quote clj-refactor)))))) (if remove-package-version (replace-regexp-in-string " (.*)" "" version) version))
  cljr--version(t)
  (list "refactor-nrepl" (cljr--version t))
  (add-to-list (quote cider-jack-in-lein-plugins) (list "refactor-nrepl" (cljr--version t)))
  (progn (add-to-list (quote cider-jack-in-lein-plugins) (list "refactor-nrepl" (cljr--version t))) (add-to-list (quote cider-jack-in-nrepl-middlewares) "refactor-nrepl.middleware/wrap-refactor"))
  (if (and cljr-inject-dependencies-at-jack-in (boundp (quote cider-jack-in-lein-plugins)) (boundp (quote cider-jack-in-nrepl-middlewares))) (progn (add-to-list (quote cider-jack-in-lein-plugins) (list "refactor-nrepl" (cljr--version t))) (add-to-list (quote cider-jack-in-nrepl-middlewares) "refactor-nrepl.middleware/wrap-refactor")))
  cljr--inject-jack-in-dependencies()
  (lambda nil (cljr--inject-jack-in-dependencies))()
  eval-after-load-helper("/home/manuel/.emacs.d/elpa/cider-20170403.402/cider.elc")
  run-hook-with-args(eval-after-load-helper "/home/manuel/.emacs.d/elpa/cider-20170403.402/cider.elc")
  do-after-load-evaluation("/home/manuel/.emacs.d/elpa/cider-20170403.402/cider.elc")
  require(cider)
  eval-buffer(#<buffer  *load*> nil "/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el" nil t)  ; Reading at buffer position 1547
  load-with-code-conversion("/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el" "/home/manuel/.emacs.d/elpa/clj-refactor-20170407.553/clj-refactor.el" nil t)
  (clj-refactor-mode 1)
  mu-clojure-mode-hook()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook clojure-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook clojure-mode-hook))
  run-mode-hooks(clojure-mode-hook)
  clojure-mode()
  set-auto-mode-0(clojure-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer twitter.clj> "~/projects/lumitweet/src/clj/lumitweet/services/twitter.clj" nil nil "~/projects/lumitweet/src/clj/lumitweet/services/twitter.clj" (6294746 66307))
  find-file-noselect("/home/manuel/projects/lumitweet/src/clj/lumitweet/services/twitter.clj" nil nil nil)
  find-file("/home/manuel/projects/lumitweet/src/clj/lumitweet/services/twitter.clj")
  #[257 "\304\305!!r\306\307\310\311\312!\313\"\314$\216\315@\316\"\210	\205
```
This is how I set up clj-refactor in my init file:
```
(use-package clj-refactor               ; Refactoring utilities
  :ensure t
  :defer t
  :init
  (defun mu-clojure-mode-hook ()
    (clj-refactor-mode 1)
    (yas-minor-mode 1)                ; For adding require/use/import
    (cljr-add-keybindings-with-prefix "C-c RET"))

  (add-hook 'clojure-mode-hook #'mu-clojure-mode-hook)
  :config
  (validate-setq cljr-suppress-middleware-warnings t
                 cljr-auto-sort-ns t
                 cljr-favor-prefix-notation
                 cljr-favor-private-functions)
  :diminish clj-refactor-mode)
```

**Comment by expez** [comment]
@manuel-uberti Are you too on emacs 26?  For now it looks like a regression in `package.el`.

**Comment by benedekfazekas** [comment]
`epl-package-from-lisp-file` seems to be the culprit. perhaps something changed in `package.el` around this in latest emacs?! will try to dig around this at some point but it is kinda low prio on my todo list. if you have same time try dig around what changed around the `epl` package in latest, 26 emacs

**Comment by manuel-uberti** [comment]
Thanks guys, I'll investigate further and report back if I find something useful.

**Comment by larsbrinkhoff** [comment]
Hi!  This is probably due to a change I made to Emacs.

It *looks* very much like in Malabarba/paradox#139, though I can't be 100% sure it's the same error.  I fixed that in Emacs commit 4fbfd7.

Can you rebuild Emacs with the very latest master, and try again?

**Comment by larsbrinkhoff** [comment]
Sorry, I see now you built from commit 291b76f91ea991c9fa8e57b55df1b68704931445, which should include my fix.

Did you do a full rebuild of Emacs?  `make bootstrap` will usually do the trick.

**Comment by manuel-uberti** [comment]
Hi @larsbrinkhoff. Thanks for the reply.

I just pulled again from master and did this from my Emacs src directory:
```
./configure --host=x86_64-debian-linux-gnu && make bootstrap && sudo make install && make clean
```
Still the same error when I try to install clj-refactor.

**Comment by larsbrinkhoff** [comment]
Yes, that should be a squeaky clean Emacs.

I tried to reproduce the problem as @rgmorris suggested in the debbugs report, but I didn't see it.

You could try backing up your .emacs.d, removing it, and trying to install clj-refactor again.  If that fixes the problem, there was a stale file in there.

**Comment by manuel-uberti** [comment]
Removing my .emacs.d did the trick. Thank you very much for your help, @larsbrinkhoff.

**Comment by benedekfazekas** [comment]
ta @larsbrinkhoff for clarifying this

**Comment by kaushalmodi** [comment]
@manuel-uberti It helps to have separate elpa dirs for different major versions of emacs. If you switch back and forth 25.1 and master (26.x) rebuilding packages in the same elpa/, it can cause issues. 

Also force byte compiling the whole elpa dir helps (or just rm the whole elpa dir and allow your config to install all the packages from scratch.

**Comment by manuel-uberti** [comment]
@kaushalmodi thank you for the tip.

I usually don't switch between Emacs versions, and just track master. :-)

**Comment by kaushalmodi** [comment]
> I usually don't switch between Emacs versions, and just track master. :-)

Ah OK. I thought of mentioning that because you said above:

> Could be, it works on 25.1.1.

I always build from master too, but I once messed up my elpa dir (when I did not have those separate for each major version) when I had to try out an older release to verify some issue for a colleague.

**Comment by maacl** [comment]
I get this issue with GNU Emacs 26.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-06-25

**Comment by ak-coram** [comment]
Same issue with GNU Emacs 26.0.50 (build 1, x86_64-unknown-freebsd11.1, Motif Version 2.3.7) of 2017-08-06 (cbea38e5c4).

**Comment by liotev** [comment]
I also got this error, it was happening when function epl-package-from-lisp-file was invoked on file clj-refactor.el. After recompiling epl.el the error disappeared, but a similar error started happening in nrepl-client.el. I recompiled it too, and the error is gone.
(My emacs-version shows "GNU Emacs 26.0.50 (build 2, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-08-07")

**Comment by iced** [comment]
Happens to me as well. Emacs 26.0.90, freshly installed with brew install `emacs --with-cocoa --devel`. Of course, I reinstalled all packages, but still getting this error. Will try to dig deeper.

**Comment by jasonjckn** [comment]
@iced Happening to me too on 26.0.90 fresh

**Comment by einSelbst** [comment]
Rebuilding all packages after upgrading from 25->26 helped, thanks all and especially @kaushalmodi !
I did:
`M-: (byte-recompile-directory package-user-dir nil 'force)`
see: https://stackoverflow.com/a/24735377/531439

**Comment by jueqingsizhe66** [comment]
> Rebuilding all packages after upgrading from 25->26 helped to solve a similar error with a different package, thanks all and especially @kaushalmodi !
> I did:
> `M-: (byte-recompile-directory package-user-dir nil 'force)`
> see: https://stackoverflow.com/a/24735377/531439

Not work in Emacs27.05. When execute (require 'clj-refactor) get the same error again.

**Comment by benedekfazekas** [comment]
have you tried the above mentioned fixes?

**Comment by jueqingsizhe66** [comment]
> 
> 
> > Rebuilding all packages after upgrading from 25->26 helped to solve a similar error with a different package, thanks all and especially @kaushalmodi !
> > I did:
> > `M-: (byte-recompile-directory package-user-dir nil 'force)`
> > see: https://stackoverflow.com/a/24735377/531439
> 
> Not work in Emacs27.05. When execute (require 'clj-refactor) get the same error again.

1. find the clj-refactor directory , delete all the elc suffix files, then `M-x byte-compile-file` , choose clj-refactor.el file
2. find the epl directory , delete the elc suffix files,  then `M-x byte-compile-file` , choose epl.el
3. restart emacs

Yes, clj-refactors works again in emacs 27.05
