### ISSUE TITLE
`seq-map-indexed` missing in emacs-25.2

### ISSUE THREAD

**Issue by otwieracz** [clojure-emacs/clj-refactor.el#379]
## Expected behavior

clj-refactor loads without errors

## Actual behavior
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "seq-25")
  require(seq-25)
  (if (fboundp (quote seq-map-indexed)) nil (require (quote seq-25)))
  eval-buffer(#<buffer  *load*> nil "/home/otwieracz/.emacs.d/elpa/clj-refactor-20170520.323/clj-refactor.el" nil t)  ; Reading at buffer position 1675
  load-with-code-conversion("/home/otwieracz/.emacs.d/elpa/clj-refactor-20170520.323/clj-refactor.el" "/home/otwieracz/.emacs.d/elpa/clj-refactor-20170520.323/clj-refactor.el" nil t)
  require(clj-refactor)
  eval((require (quote clj-refactor)) nil)
  eval-expression((require (quote clj-refactor)) nil)
  funcall-interactively(eval-expression (require (quote clj-refactor)) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

## Steps to reproduce the problem

`(require 'clj-refactor)` on emacs-25.2

## Additional info

There is no `seq-map-indexed` which is used as a check if it's already emacs 25
https://github.com/emacs-mirror/emacs/blob/emacs-25.2/lisp/emacs-lisp/seq.el

https://github.com/NicolasPetton/seq.el says it's included in emacs-25.

`emacs-25.2` is most recent stable available.

### clj-refactor.el version information

`  clj-refactor       20170520.323  installed             A collection of clojure refactoring functions`

### CIDER version information

`  cider              20170525.255  installed             Clojure Interactive Development Environment that Rocks
`
### Emacs version

`GNU Emacs 25.2.1 (x86_64-pc-linux-gnu) of 2017-05-22`

### Operating system

Gentoo Linux

**Comment by benedekfazekas** [comment]
yeah this is a bit of mess. your error is rather that `seq-25` is not found on your load path. and as far as i understand `seq-map-indexed` is in `seq-25` which gets loaded if you are on emacs 25 AND high enough seq.el version.

so could you please reinstall clj-refactor and/or seq.el. that should fix this. let me know by reopening this if it does not.

**Comment by enaeher** [comment]
I am having the same problem. Installing `seq` from ELPA does not resolve it, nor does reinstalling `clj-refactor`.

**Comment by benedekfazekas** [comment]
@dotemacs any idea?

**Comment by dotemacs** [comment]
I'll have a look tonight!

**Comment by dotemacs** [comment]
So it seems that this only happens with spacemacs, despite the fact that Emacs is on version 25.2.1?

I'm on the same version, but I don't see this behaviour.

Can you try to reproduce this with vanilla Emacs setup, just to make sure that no other package is interfering with clj-refactor?

Try the following:

1. move your .emacs.d out of the way: `mv .emacs.d .emacs.d-$(date +%Y-%M-%d)`
1. start emacs: `emacs -Q`
1. `M-x package-install RET clj-refactor RET`
1. `M-x package-install RET cider RET`

Then go to the directory where you have your Clojure project:

1. `M-x cider-jack-in RET`

What happens now?

**Comment by dotemacs** [comment]
@otwieracz please see the above

**Comment by dotemacs** [comment]
@enaeher ditto

**Comment by enaeher** [comment]
@dotemacs following your instructions, I am able to install clj-refactor and run `cider-jack-in` with no issues. I am still unable to load it with my normal configuration. (FWIW, I do not use Spacemacs, just regular Emacs 25.2.1 installed via Homebrew.)

**Comment by dotemacs** [comment]
@enaeher thanks for the feedback. Glad to hear that it's working OK in plain, bare Emacs.

It seems to me that the issue potentially lies your other packages and/or your normal configuration.

Can you try to start with the bare Emacs and bring in packages one by one as and when you need them? That way you'll be able to pinpoint the issue with more certainty.

**Comment by benedekfazekas** [comment]
any progress on  this. sorry for nagging @enaeher but want to make sure the lately released 2.3.1 does not have a deps problem

**Comment by enaeher** [comment]
Hi,

I haven't been able to find anything conclusive. Here is what I tried:

I removed my `.emacs` and removed everything from `.emacs.d` except for clj-refactor, cider, and their dependencies:

```
~ $ ll .emacs.d/
total 0
drwx------   3 eli  staff   102B Jun 23 10:21 auto-save-list
drwxr-xr-x  19 eli  staff   646B Jun 23 10:21 elpa
~ $ ll .emacs.d/elpa
total 16
drwxr-xr-x  58 eli  staff   1.9K Jun 23 10:21 cider-20170620.207
drwxr-xr-x   9 eli  staff   306B Jun 23 10:21 clj-refactor-20170608.320
-rw-r--r--   1 eli  staff    66B Jun 23 10:21 clj-refactor-readme.txt
drwxr-xr-x   6 eli  staff   204B Jun 23 10:21 clojure-mode-20170608.2315
drwxr-xr-x   7 eli  staff   238B Jun 23 10:21 edn-20160215.419
drwxr-xr-x   7 eli  staff   238B Jun 23 10:21 epl-20150517.433
drwxr-xr-x  11 eli  staff   374B Jun 23 10:21 hydra-20170325.815
drwxr-xr-x   6 eli  staff   204B Jun 23 10:21 inflections-20161126.1727
drwxr-xr-x  22 eli  staff   748B Jun 23 10:21 multiple-cursors-20170215.552
drwxr-xr-x   6 eli  staff   204B Jun 23 10:21 paredit-20170405.1149
drwxr-xr-x   7 eli  staff   238B Jun 23 10:21 peg-20150707.2341
drwxr-xr-x   7 eli  staff   238B Jun 23 10:21 pkg-info-20150517.443
drwxr-xr-x   7 eli  staff   238B Jun 23 10:21 queue-0.1.1
drwxr-xr-x   6 eli  staff   204B Jun 23 10:21 s-20170428.1026
drwxr-xr-x   6 eli  staff   204B Jun 23 10:21 spinner-1.7.3
-rw-r--r--   1 eli  staff   147B Jun 23 10:21 spinner-1.7.3.signed
drwxr-xr-x   7 eli  staff   238B Jun 23 10:21 yasnippet-20170605.1940
~ $
```

Even with this bare-bones configuration, I get this error when trying to eval `(require 'clj-refactor)`:

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "seq-25")
  require(seq-25)
  byte-code("\300\301!\210\302\303!\204\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315!\210\300\316!\210\300\317!\210\320\321\322\323\324DD\325\326\327\330\331&\210\320\332\322\323\333DD\334\326\327\330\331&\210\320\335\322\323\336DD\337\326\327\330\340&\210\320\341\322\323\342DD\343\330\344\326\327&\210\320\345\322\323\346DD\347\326\327\330\331&\210\320\350\322\323\351DD\352\326\327\330\353&\210\320\354\322\323\355DD\356\326\327\330\357&\210\320\360\322\323\361DD\362\326\327\330\331&\210\320\363\322\323\364DD\365\326\327\330\331&\210\320\366\322\323\367DD\370\326\327\330\331&\210\320\371\322\323\372DD\373\326\327\330\331&\210\320\374\322\323\375DD\376\326\327\330\331&\210\320\377\322\323\201@DD\201A\326\327\330\331&\210\320\201B\322\323\201CDD\201D\326\327\330\331&\210\320\201E\322\323\201FDD\201G\326\327\330\331&\210\320\201H\322\323\201IDD\201J\326\327\330\331&\210\320\201K\322\323\201LDD\201M\326\327\330\331&\210\320\201N\322\323\201ODD\201P\326\327\330\331&\210\320\201Q\322\323\201RDD\201S\326\327\330\331&\210\320\201T\322\323\201UDD\201V\326\327\330\201W&\210\320\201X\322\323\201YDD\201Z\326\327\330\201W&\210\320\201[\322\323\201\\DD\201]\326\327\330\201W&\210\320\201^\322\323\201_DD\201`\326\327\330\201W&\210\320\201a\322\323\201bDD\201c\326\327\330\201W&\210\320\201d\322\323\201eDD\201f\326\327\330\201W&\210\320\201g\322\323\201hDD\201i\326\327\330\331&\210\320\201j\322\323\201kDD\201l\326\327\330\201m&\207" [require seq fboundp seq-map-indexed seq-25 clj-refactor-compat yasnippet paredit multiple-cursors-core clojure-mode cider edn sgml-mode inflections hydra subword custom-declare-variable cljr-add-ns-to-blank-clj-files funcall function #[0 "\300\207" [t] 1] "If t, automatically add a ns form to new .clj files." :group cljr :type boolean cljr-auto-sort-ns #[0 "\300\207" [t] 1] "If t, sort ns form after any command that changes it." cljr-magic-requires #[0 "\300\207" [t] 1] "Whether to automatically require common namespaces when they are used.\nThese are the namespaces listed in `cljr-magic-require-namespaces'.\n\nIf this variable is `:prompt', typing the short form followed by\n`\\[cljr-slash]' will ask if you want to add the corresponding require\nstatement to the ns form.\nAny other non-nil value means to add the form without asking." (choice (const :tag "true" t) (const :tag "prompt" :prompt) (const :tag "false" nil)) cljr-magic-require-namespaces #[0 "\300\207" [(("io" . "clojure.java.io") ("set" . "clojure.set") ("str" . "clojure.string") ("walk" . "clojure.walk") ("zip" . "clojure.zip"))] 1] "Alist of aliases and namespaces used by `cljr-slash'." (repeat (cons (string :tag "Short alias") (string :tag "Full namespace"))) cljr-project-clean-prompt #[0 "\300\207" [t] 1] "If t, `cljr-project-clean' asks before doing anything.\nIf nil, the project clean functions are run without warning." cljr-project-clean-functions #[0 "\300C\207" [cljr-clean-ns] 1] "List of functions called by `cljr-project-clean'.\nThese are called on all .clj files in the project." (repeat function) cljr-project-clean-exceptions #[0 "\300\207" [("dev/user.clj" "project.clj" "boot.clj")] 1] "A list of files that `cljr-project-clean' should avoid." (repeat string) cljr-hotload-dependencies #[0 "\300\207" [t] 1] ...] 8)
  require(clj-refactor)
  eval((require (quote clj-refactor)) nil)
  eval-expression((require (quote clj-refactor)) nil)
  funcall-interactively(eval-expression (require (quote clj-refactor)) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I am not sure why this behavior is different from what I saw when using package-install above.

**Comment by dotemacs** [comment]
What is your initialisation file:

- ~/.emacs.d/init.el ?
- ~/.emacs ?
- ~/.emacs.el ?

What do you have in it?

**Comment by enaeher** [comment]
During the test above, I had no initialization file.

My normal .emacs is at https://github.com/enaeher/dotfiles-emacs.

**Comment by dotemacs** [comment]
Thank you.

Without your initialization file, can you do the following:

`M-x list-load-path-shadows`

What does that show you ?

Then look at the output of this which you should eval in the \*scratch\* buffer:

```emacs-lisp
(insert (format "\nload-path: %s\n" load-path))
```

**Comment by f0086** [comment]
I have the same problem (ArchLinux, stock Emacs 25.2.1)

list-load-path-shadows:
```
/home/aaron/.emacs.d/el-get/spaceline/tests hides /home/aaron/.emacs.d/el-get/fringe-helper/tests
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-meta hides /usr/share/emacs/site-lisp/mu4e/mu4e-meta
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-view hides /usr/share/emacs/site-lisp/mu4e/mu4e-view
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-utils hides /usr/share/emacs/site-lisp/mu4e/mu4e-utils
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-message hides /usr/share/emacs/site-lisp/mu4e/mu4e-message
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-lists hides /usr/share/emacs/site-lisp/mu4e/mu4e-lists
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-main hides /usr/share/emacs/site-lisp/mu4e/mu4e-main
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e hides /usr/share/emacs/site-lisp/mu4e/mu4e
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-compose hides /usr/share/emacs/site-lisp/mu4e/mu4e-compose
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-mark hides /usr/share/emacs/site-lisp/mu4e/mu4e-mark
/home/aaron/.emacs.d/el-get/mu4e/mu4e/org-mu4e hides /usr/share/emacs/site-lisp/mu4e/org-mu4e
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-contrib hides /usr/share/emacs/site-lisp/mu4e/mu4e-contrib
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-headers hides /usr/share/emacs/site-lisp/mu4e/mu4e-headers
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-context hides /usr/share/emacs/site-lisp/mu4e/mu4e-context
/home/aaron/.emacs.d/el-get/mu4e/mu4e/org-old-mu4e hides /usr/share/emacs/site-lisp/mu4e/org-old-mu4e
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-actions hides /usr/share/emacs/site-lisp/mu4e/mu4e-actions
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-speedbar hides /usr/share/emacs/site-lisp/mu4e/mu4e-speedbar
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-draft hides /usr/share/emacs/site-lisp/mu4e/mu4e-draft
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-proc hides /usr/share/emacs/site-lisp/mu4e/mu4e-proc
/home/aaron/.emacs.d/el-get/mu4e/mu4e/mu4e-vars hides /usr/share/emacs/site-lisp/mu4e/mu4e-vars
/usr/share/emacs/site-lisp/flim/hex-util hides /usr/share/emacs/25.2/lisp/hex-util
/usr/share/emacs/site-lisp/flim/md4 hides /usr/share/emacs/25.2/lisp/md4
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-perl hides /usr/share/emacs/25.2/lisp/org/ob-perl
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-timer hides /usr/share/emacs/25.2/lisp/org/org-timer
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-docview hides /usr/share/emacs/25.2/lisp/org/org-docview
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-id hides /usr/share/emacs/25.2/lisp/org/org-id
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-scala hides /usr/share/emacs/25.2/lisp/org/ob-scala
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-ruby hides /usr/share/emacs/25.2/lisp/org/ob-ruby
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-protocol hides /usr/share/emacs/25.2/lisp/org/org-protocol
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-w3m hides /usr/share/emacs/25.2/lisp/org/org-w3m
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-bibtex hides /usr/share/emacs/25.2/lisp/org/org-bibtex
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-scheme hides /usr/share/emacs/25.2/lisp/org/ob-scheme
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-ledger hides /usr/share/emacs/25.2/lisp/org/ob-ledger
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-ocaml hides /usr/share/emacs/25.2/lisp/org/ob-ocaml
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-attach hides /usr/share/emacs/25.2/lisp/org/org-attach
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-python hides /usr/share/emacs/25.2/lisp/org/ob-python
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-makefile hides /usr/share/emacs/25.2/lisp/org/ob-makefile
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-rmail hides /usr/share/emacs/25.2/lisp/org/org-rmail
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob hides /usr/share/emacs/25.2/lisp/org/ob
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-clock hides /usr/share/emacs/25.2/lisp/org/org-clock
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-capture hides /usr/share/emacs/25.2/lisp/org/org-capture
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-crypt hides /usr/share/emacs/25.2/lisp/org/org-crypt
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-eshell hides /usr/share/emacs/25.2/lisp/org/org-eshell
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-clojure hides /usr/share/emacs/25.2/lisp/org/ob-clojure
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-macro hides /usr/share/emacs/25.2/lisp/org/org-macro
/home/aaron/.emacs.d/el-get/org-mode/lisp/org hides /usr/share/emacs/25.2/lisp/org/org
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-texinfo hides /usr/share/emacs/25.2/lisp/org/ox-texinfo
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-feed hides /usr/share/emacs/25.2/lisp/org/org-feed
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-R hides /usr/share/emacs/25.2/lisp/org/ob-R
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-man hides /usr/share/emacs/25.2/lisp/org/ox-man
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-awk hides /usr/share/emacs/25.2/lisp/org/ob-awk
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-maxima hides /usr/share/emacs/25.2/lisp/org/ob-maxima
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-lob hides /usr/share/emacs/25.2/lisp/org/ob-lob
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-latex hides /usr/share/emacs/25.2/lisp/org/ox-latex
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-ditaa hides /usr/share/emacs/25.2/lisp/org/ob-ditaa
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-octave hides /usr/share/emacs/25.2/lisp/org/ob-octave
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-table hides /usr/share/emacs/25.2/lisp/org/ob-table
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-screen hides /usr/share/emacs/25.2/lisp/org/ob-screen
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-gnuplot hides /usr/share/emacs/25.2/lisp/org/ob-gnuplot
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-compat hides /usr/share/emacs/25.2/lisp/org/org-compat
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-fortran hides /usr/share/emacs/25.2/lisp/org/ob-fortran
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-calc hides /usr/share/emacs/25.2/lisp/org/ob-calc
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-faces hides /usr/share/emacs/25.2/lisp/org/org-faces
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-tangle hides /usr/share/emacs/25.2/lisp/org/ob-tangle
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-matlab hides /usr/share/emacs/25.2/lisp/org/ob-matlab
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-js hides /usr/share/emacs/25.2/lisp/org/ob-js
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-mouse hides /usr/share/emacs/25.2/lisp/org/org-mouse
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-org hides /usr/share/emacs/25.2/lisp/org/ox-org
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-picolisp hides /usr/share/emacs/25.2/lisp/org/ob-picolisp
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-sqlite hides /usr/share/emacs/25.2/lisp/org/ob-sqlite
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-md hides /usr/share/emacs/25.2/lisp/org/ox-md
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-exp hides /usr/share/emacs/25.2/lisp/org/ob-exp
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-table hides /usr/share/emacs/25.2/lisp/org/org-table
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-css hides /usr/share/emacs/25.2/lisp/org/ob-css
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-src hides /usr/share/emacs/25.2/lisp/org/org-src
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-mscgen hides /usr/share/emacs/25.2/lisp/org/ob-mscgen
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-io hides /usr/share/emacs/25.2/lisp/org/ob-io
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-eval hides /usr/share/emacs/25.2/lisp/org/ob-eval
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-haskell hides /usr/share/emacs/25.2/lisp/org/ob-haskell
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-java hides /usr/share/emacs/25.2/lisp/org/ob-java
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-plantuml hides /usr/share/emacs/25.2/lisp/org/ob-plantuml
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-asymptote hides /usr/share/emacs/25.2/lisp/org/ob-asymptote
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-gnus hides /usr/share/emacs/25.2/lisp/org/org-gnus
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-beamer hides /usr/share/emacs/25.2/lisp/org/ox-beamer
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-org hides /usr/share/emacs/25.2/lisp/org/ob-org
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-sass hides /usr/share/emacs/25.2/lisp/org/ob-sass
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-footnote hides /usr/share/emacs/25.2/lisp/org/org-footnote
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-plot hides /usr/share/emacs/25.2/lisp/org/org-plot
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-core hides /usr/share/emacs/25.2/lisp/org/ob-core
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-entities hides /usr/share/emacs/25.2/lisp/org/org-entities
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-comint hides /usr/share/emacs/25.2/lisp/org/ob-comint
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-version hides /usr/share/emacs/25.2/lisp/org/org-version
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-sql hides /usr/share/emacs/25.2/lisp/org/ob-sql
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-ascii hides /usr/share/emacs/25.2/lisp/org/ox-ascii
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-icalendar hides /usr/share/emacs/25.2/lisp/org/ox-icalendar
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-irc hides /usr/share/emacs/25.2/lisp/org/org-irc
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-odt hides /usr/share/emacs/25.2/lisp/org/ox-odt
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-keys hides /usr/share/emacs/25.2/lisp/org/ob-keys
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-ref hides /usr/share/emacs/25.2/lisp/org/ob-ref
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-archive hides /usr/share/emacs/25.2/lisp/org/org-archive
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-lisp hides /usr/share/emacs/25.2/lisp/org/ob-lisp
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-lilypond hides /usr/share/emacs/25.2/lisp/org/ob-lilypond
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-html hides /usr/share/emacs/25.2/lisp/org/ox-html
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-element hides /usr/share/emacs/25.2/lisp/org/org-element
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-pcomplete hides /usr/share/emacs/25.2/lisp/org/org-pcomplete
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-mhe hides /usr/share/emacs/25.2/lisp/org/org-mhe
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-indent hides /usr/share/emacs/25.2/lisp/org/org-indent
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-shen hides /usr/share/emacs/25.2/lisp/org/ob-shen
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-loaddefs hides /usr/share/emacs/25.2/lisp/org/org-loaddefs
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-ctags hides /usr/share/emacs/25.2/lisp/org/org-ctags
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-latex hides /usr/share/emacs/25.2/lisp/org/ob-latex
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-habit hides /usr/share/emacs/25.2/lisp/org/org-habit
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-mobile hides /usr/share/emacs/25.2/lisp/org/org-mobile
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox hides /usr/share/emacs/25.2/lisp/org/ox
/home/aaron/.emacs.d/el-get/org-mode/lisp/ox-publish hides /usr/share/emacs/25.2/lisp/org/ox-publish
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-dot hides /usr/share/emacs/25.2/lisp/org/ob-dot
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-install hides /usr/share/emacs/25.2/lisp/org/org-install
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-agenda hides /usr/share/emacs/25.2/lisp/org/org-agenda
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-list hides /usr/share/emacs/25.2/lisp/org/org-list
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-C hides /usr/share/emacs/25.2/lisp/org/ob-C
/home/aaron/.emacs.d/el-get/org-mode/lisp/ob-emacs-lisp hides /usr/share/emacs/25.2/lisp/org/ob-emacs-lisp
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-datetree hides /usr/share/emacs/25.2/lisp/org/org-datetree
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-inlinetask hides /usr/share/emacs/25.2/lisp/org/org-inlinetask
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-bbdb hides /usr/share/emacs/25.2/lisp/org/org-bbdb
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-colview hides /usr/share/emacs/25.2/lisp/org/org-colview
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-macs hides /usr/share/emacs/25.2/lisp/org/org-macs
/home/aaron/.emacs.d/el-get/org-mode/lisp/org-info hides /usr/share/emacs/25.2/lisp/org/org-info
/usr/share/emacs/site-lisp/flim/hmac-md5 hides /usr/share/emacs/25.2/lisp/net/hmac-md5
/usr/share/emacs/site-lisp/flim/hmac-def hides /usr/share/emacs/25.2/lisp/net/hmac-def
/usr/share/emacs/site-lisp/flim/sasl-cram hides /usr/share/emacs/25.2/lisp/net/sasl-cram
/usr/share/emacs/site-lisp/flim/sasl hides /usr/share/emacs/25.2/lisp/net/sasl
/usr/share/emacs/site-lisp/flim/ntlm hides /usr/share/emacs/25.2/lisp/net/ntlm
/usr/share/emacs/site-lisp/flim/sasl-ntlm hides /usr/share/emacs/25.2/lisp/net/sasl-ntlm
/usr/share/emacs/site-lisp/flim/sasl-digest hides /usr/share/emacs/25.2/lisp/net/sasl-digest
/usr/share/emacs/site-lisp/semi/smime hides /usr/share/emacs/25.2/lisp/gnus/smime
/usr/share/emacs/site-lisp/semi/pgg-pgp hides /usr/share/emacs/25.2/lisp/obsolete/pgg-pgp
/usr/share/emacs/site-lisp/semi/pgg-def hides /usr/share/emacs/25.2/lisp/obsolete/pgg-def
/usr/share/emacs/site-lisp/semi/pgg-pgp5 hides /usr/share/emacs/25.2/lisp/obsolete/pgg-pgp5
/usr/share/emacs/site-lisp/semi/pgg-gpg hides /usr/share/emacs/25.2/lisp/obsolete/pgg-gpg
/usr/share/emacs/site-lisp/semi/pgg hides /usr/share/emacs/25.2/lisp/obsolete/pgg
/usr/share/emacs/site-lisp/semi/pgg-parse hides /usr/share/emacs/25.2/lisp/obsolete/pgg-parse

141 Emacs Lisp load-path shadowings were found
```

load-path output:
```
load-path: (/home/aaron/.emacs.d/el-get/company-tern /home/aaron/.emacs.d/el-get/company-mode /home/aaron/.emacs.d/el-get/tern/emacs /home/aaron/.emacs.d/el-get/skewer-mode /home/aaron/.emacs.d/el-get/simple-httpd /home/aaron/.emacs.d/el-get/js2-mode /home/aaron/.emacs.d/el-get/cljsbuild-mode /home/aaron/.emacs.d/el-get/inf-ruby /home/aaron/.emacs.d/el-get/bm /home/aaron/.emacs.d/el-get/pos-tip /home/aaron/.emacs.d/el-get/evil-mc /home/aaron/.emacs.d/el-get/ac-php /home/aaron/.emacs.d/el-get/auto-complete /home/aaron/.emacs.d/el-get/fuzzy /home/aaron/.emacs.d/el-get/xcscope /home/aaron/.emacs.d/el-get/which-key /home/aaron/.emacs.d/el-get/sicp /home/aaron/.emacs.d/el-get/flyspell /home/aaron/.emacs.d/el-get/langtool /home/aaron/.emacs.d/el-get/markdown-mode /home/aaron/.emacs.d/el-get/dockerfile-mode /home/aaron/.emacs.d/el-get/web-mode /home/aaron/.emacs.d/el-get/yaml-mode /home/aaron/.emacs.d/el-get/coffee-mode /home/aaron/.emacs.d/el-get/sass-mode /home/aaron/.emacs.d/el-get/haml-mode /home/aaron/.emacs.d/el-get/go-mode /home/aaron/.emacs.d/el-get/php-mode /home/aaron/.emacs.d/el-get/clj-refactor /home/aaron/.emacs.d/el-get/edn /home/aaron/.emacs.d/el-get/peg /home/aaron/.emacs.d/el-get/cider /home/aaron/.emacs.d/el-get/queue /home/aaron/.emacs.d/el-get/spinner /home/aaron/.emacs.d/el-get/inflections /home/aaron/.emacs.d/el-get/multiple-cursors /home/aaron/.emacs.d/el-get/yasnippet /home/aaron/.emacs.d/el-get/clojure-mode /home/aaron/.emacs.d/el-get/flycheck /home/aaron/.emacs.d/el-get/mu4e/mu4e /home/aaron/.emacs.d/el-get/popwin/misc /home/aaron/.emacs.d/el-get/popwin /home/aaron/.emacs.d/el-get/f /home/aaron/.emacs.d/el-get/spaceline /home/aaron/.emacs.d/el-get/s /home/aaron/.emacs.d/el-get/git-gutter-fringe+ /home/aaron/.emacs.d/el-get/fringe-helper /home/aaron/.emacs.d/el-get/git-gutter+ /home/aaron/.emacs.d/el-get/linum-off /home/aaron/.emacs.d/el-get/neotree /home/aaron/.emacs.d/el-get/popup /home/aaron/.emacs.d/el-get/hydra /home/aaron/.emacs.d/el-get/aggressive-indent-mode /home/aaron/.emacs.d/el-get/names /home/aaron/.emacs.d/el-get/powerline /home/aaron/.emacs.d/el-get/helm-projectile /home/aaron/.emacs.d/el-get/projectile /home/aaron/.emacs.d/el-get/pkg-info /home/aaron/.emacs.d/el-get/epl /home/aaron/.emacs.d/el-get/rainbow-delimiters /home/aaron/.emacs.d/el-get/paredit /home/aaron/.emacs.d/el-get/helm-dictionary /home/aaron/.emacs.d/el-get/helm /home/aaron/.emacs.d/el-get/magit/lisp/ /home/aaron/.emacs.d/el-get/emacs-async /home/aaron/.emacs.d/el-get/with-editor /home/aaron/.emacs.d/el-get/dash /home/aaron/.emacs.d/el-get/evil-surround /home/aaron/.emacs.d/el-get/evil-org-mode /home/aaron/.emacs.d/el-get/evil-leader /home/aaron/.emacs.d/el-get/evil /home/aaron/.emacs.d/el-get/goto-chg /home/aaron/.emacs.d/el-get/undo-tree /home/aaron/.emacs.d/el-get/el-get /home/aaron/.emacs.d/el-get/org-mode/lisp /home/aaron/.emacs.d/el-get/org-mode/contrib/lisp /home/aaron/.emacs.d/el-get/org-mode /home/aaron/.emacs.d/el-get/ /home/aaron/.emacs.d/el-get/el-get/methods ~/.emacs.d/el-get/el-get /home/aaron/.emacs.d/elpa/queue-0.1.1 /usr/share/emacs/25.2/site-lisp /usr/share/emacs/site-lisp /usr/share/emacs/site-lisp/apel /usr/share/emacs/site-lisp/emu /usr/share/emacs/site-lisp/flim /usr/share/emacs/site-lisp/mu4e /usr/share/emacs/site-lisp/semi /usr/share/emacs/site-lisp/wl /usr/share/emacs/25.2/lisp /usr/share/emacs/25.2/lisp/vc /usr/share/emacs/25.2/lisp/url /usr/share/emacs/25.2/lisp/textmodes /usr/share/emacs/25.2/lisp/progmodes /usr/share/emacs/25.2/lisp/play /usr/share/emacs/25.2/lisp/org /usr/share/emacs/25.2/lisp/nxml /usr/share/emacs/25.2/lisp/net /usr/share/emacs/25.2/lisp/mh-e /usr/share/emacs/25.2/lisp/mail /usr/share/emacs/25.2/lisp/leim /usr/share/emacs/25.2/lisp/language /usr/share/emacs/25.2/lisp/international /usr/share/emacs/25.2/lisp/gnus /usr/share/emacs/25.2/lisp/eshell /usr/share/emacs/25.2/lisp/erc /usr/share/emacs/25.2/lisp/emulation /usr/share/emacs/25.2/lisp/emacs-lisp /usr/share/emacs/25.2/lisp/cedet /usr/share/emacs/25.2/lisp/calendar /usr/share/emacs/25.2/lisp/calc /usr/share/emacs/25.2/lisp/obsolete)
```

**Comment by dotemacs** [comment]
Hello @f0086 

I see you're using el-get fetch the packages.

I'll ask you to try two different things.

First, can you reduce your initialisation config to the bare minimum and just install clj-refactor?
Then load the project. What happens then?

Now for the second option:

Not sure what version of clj-refactor you're on, but I'm on 2.3.1. Amongst the dependencies listed for it is `seq 2.19`. Which is installed, despite the fact that `seq 2.3` is built in. 

When I list list-load-path-shadows, I can see that: seq-2.19 hides built in seq, which is at 2.3.

Can you try to install `seq 2.19` explicitly, and report back?

**Comment by f0086** [comment]
Ok, I've found my problem.
I had a ```(require 'clj-refactor)``` in mt init-file, which loads _before_ the initialization for the seq package happened. Removing the require solves my problem.

On this journey I've fixed some dependency problems for clj-refactor on el-get
https://github.com/dimitri/el-get/pull/2521#issuecomment-311147595

**Comment by wiseman** [comment]
I'm running into this same error.  I had a `(require 'clj-refactor)` in my init file, but after removing it I still get the error. Installed versions: `cider 20171219.1034`, `clj-refactor 20171117.317`, ` seq 20151028.759`
